version:  '3.7'
services:
    nginx:
        container_name: laravel_nginx
        image: nginx:1.15.3-alpine
        restart: unless-stopped
        volumes:
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - '.:/usr/src/app:rw'
        ports:
            - "8000:80"
    mysql:
        container_name: laravel_mysql
        image: mysql:5
        restart: unless-stopped
        user: 999:999
        ports:
            - "3330:3306"
        volumes:
            - 'mysql-vol:/var/lib/mysql'
        env_file:
            - .env
    php:
        container_name: laravel_php
        build:
            context: .
            dockerfile: Dockerfile
        user: 1000:1000
        volumes:
            - './docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
            - './docker/php/php.ini:/usr/local/etc/php/php.ini:ro'
            - '.:/usr/src/app:rw'
        env_file:
            - .env
        depends_on:
            - mysql
            - nginx

volumes:
  mysql-vol:
    name: laravel_mysql_data

